export type { MapPoint, PixelMap } from './types'
export { createPlaneMap, planePoint, squarePlaneDims } from './plane'
export type { PlaneParams } from './plane'
export { createCubeMap, cubePoint, cubePixelCount } from './cube'
export type { CubeParams } from './cube'
export { createCustomMap, inferDim } from './custom'
export type { Coord } from './custom'
